dark-side/ai-collaboration-platform

config/application.rb
config/environments/development.rb
config/environments/production.rb

http://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=979&view=detail&selectedIssue=LVRUBY-20
Send confirmation email after registration
Fixed Mailer at production

LVRUBY-20: Fix mailer at production

---

.haml-lint.yml
.hound.yml
app/views/layouts/application.html.haml
db/migrate/20190422130423_add_remember_created_at_to_users.rb
db/schema.rb

Fix remember me
Add new migration - add column 'remember_created_at' to Users table

fix_LVRUBY-10: Fix 'Remember me'

---

app/views/devise/confirmations/new.html.haml
app/views/devise/passwords/edit.html.haml
app/views/devise/passwords/new.html.haml

http://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=979&view=detavil&selectedIssue=LVRUBY-88
_Please provide the details of the issue._
Add styles for password forms

LVRUBY-88: Add styles for password forms

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/views/layouts/application.html.haml
app/views/shared/_footer.html.haml
app/views/shared/_header.html.haml
config/application.rb
config/locales/en.yml
config/locales/uk.yml
config/routes.rb
db/schema.rb
spec/factories/users.rb
spec/rails_helper.rb
spec/views/shared/_header.html.haml_spec.rb

[LVRUBY-40](http://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=979&view=planning&selectedIssue=LVRUBY-40)
Add navigation menu so I’ll see it at all pages.
Add user email to menu right corner if user signed in.
Add 'logout', 'edit profile' button to right corner if user is signed in.
Add 'login' , 'sign up' button to right corner if user is not logged in.
Add I18n to menu.
Add buttons to the footer, to change locale.
Navigation menu added by adding 2 files: _header.html.haml and _footer.html.haml.
If user logged in , there would be his email, 'Log out' button and 'Edit profile' button at menu right corner.
If user is not logged in there would be 'log in' and 'sign up' button at menu right corner.
I18n added to menu.
Buttons to change locale added to the footer.

LVRUBY-40: Created menu layout

---

.rubocop.yml
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/pages/news.scss
app/controllers/application_controller.rb
app/controllers/news_controller.rb
app/models/news.rb
app/models/user.rb
app/views/news/_aside_bar.html.haml
app/views/news/_form.html.haml
app/views/news/_related_news.html.haml
app/views/news/edit.html.haml
app/views/news/index.html.haml
app/views/news/new.html.haml
app/views/news/show.html.haml
config/locales/en.yml
config/locales/uk.yml
config/routes.rb
config/tinymce.yml
db/migrate/20190418070117_create_news.rb
db/schema.rb
spec/controllers/news_controller_spec.rb
spec/factories/news.rb
spec/factories/users.rb
spec/models/news_spec.rb
spec/models/user_spec.rb

https://ssu-jira.softserveinc.com/browse/LVRUBY-66
Create model News with fields title, details, information, user_id
Create controller for news
Create views for news
Created views, controller, model for news
Added gem wysiswyg for editing text in news/_form.html.haml
Created assosiation between User and News models

LVRUBY 66 Create News model

---

db/migrate/20190502094727_add_approved_to_users.rb
db/schema.rb

http://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=979&view=detail&selectedIssue=LVRUBY-19&quickFilter=2834
Add approved column in User model
Add approved column in User model

LVRUBY-19: add approved column to Users table

---

app/controllers/news_controller.rb
app/views/news/index.html.haml
db/migrate/20190427114834_add_views_counter_column_to_news.rb
db/schema.rb
spec/controllers/news_controller_spec.rb

https://ssu-jira.softserveinc.com/browse/LVRUBY-50
Add views counter to news model
Added field views in News table

LVRUBY-50: Add views counter to news model

---

db/migrate/20190507081542_add_approved_to_news.rb
db/schema.rb

http://ssu-jira.softserveinc.com/browse/LVRUBY-12
Add approved column to news
Add approved column to news

LVRUBY-12: Add approvement to news

---

app/assets/javascripts/news.js
app/views/news/_form.html.haml
app/views/shared/_header.html.haml
config/locales/en.yml
config/locales/uk.yml

http://ssu-jira.softserveinc.com/browse/LVRUBY-89
Add link 'Create News' to header
Added link 'Create News' to header

LVRUBY-73: Add Create News link to header

---

app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/pages/contact_us.scss
app/controllers/messages_controller.rb
app/mailers/messages_mailer.rb
app/models/message.rb
app/views/application/contact_us.html.haml
app/views/messages_mailer/contact_us_email.html.haml
app/views/shared/_footer.html.haml
app/views/shared/_header.html.haml
config/locales/en.yml
config/locales/uk.yml
config/routes.rb
db/schema.rb
spec/controllers/messages_controller_spec.rb
spec/factories/messages.rb
spec/mailers/messages_mailer_spec.rb
spec/models/message_spec.rb

https://ssu-jira.softserveinc.com/browse/LVRUBY-94
_Please list your code reviewers here._
Add page contact us
Added page contact us
Created mailer for sending message to dark-side email

LVRUBY-94: Add contact us form

---

Procfile
config/initializers/redis.rb
config/initializers/sidekiq.rb

fix LVRUBY-55
Add file config/initializers/redis.rb for deploy
Add file config/initializers/redis.rb for deploy

Fix lvruby 55: Add redis.rb

---

app/assets/javascripts/application.js
app/assets/stylesheets/pages/layout.scss
app/views/news/_share_buttons.html.haml

Jquery was not compiled in production
Changed order of js files in application.js

Fixed js order for better compiling

---

app/assets/stylesheets/pages/comments.scss
app/controllers/comments_controller.rb
app/controllers/news_controller.rb
app/models/comment.rb
app/models/news.rb
app/models/user.rb
app/views/comments/_comment.html.haml
app/views/comments/_form.html.haml
app/views/news/show.html.haml
config/locales/en.yml
config/locales/uk.yml
config/routes.rb
db/migrate/20190503123952_create_comments.rb
db/schema.rb
spec/controllers/comments_controller_spec.rb
spec/factories/comment.rb
spec/models/comment_spec.rb

[LVRUBY-74](http://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=979&view=detail&selectedIssue=LVRUBY-74&quickFilter=2834)
Add nested comments to news, specs for comments, I18n.
Create comment model, controller with #create, #destroy actions. Comment model has polymorphic relations with commentable which are for now News and Comment(as reply to comment). Also added specs for Comment model validations and associations and specs for CommentsController actions. I18n added.

LVRUBY-74:create comments model, controller, add specs

---

app/controllers/application_controller.rb
app/controllers/devise_overrides/registrations_controller.rb
app/models/role.rb
app/models/user.rb
app/views/devise/registrations/new.html.haml
config/routes.rb
db/migrate/20190507071810_create_roles.rb
db/migrate/20190507071955_create_join_table.rb
db/migrate/20190509145032_add_index_to_roles.rb
db/schema.rb
db/seeds.rb
spec/factories/roles.rb
spec/models/roles_spec.rb
spec/models/user_spec.rb

http://ssu-jira.softserveinc.com/browse/LVRUBY-89
Create roles
Create roles

LVRUBY-89: Implement users' roles

---

Gemfile
Gemfile.lock
app/assets/stylesheets/pages/filter.scss
app/assets/stylesheets/pages/news.scss
app/controllers/news_controller.rb
app/models/news.rb
app/views/news/_form.html.haml
app/views/news/_selector.html.haml
app/views/news/index.html.haml
config/locales/en.yml
config/locales/uk.yml
db/migrate/20190426144853_add_category_to_news.rb
db/schema.rb
spec/controllers/news_controller_spec.rb
spec/factories/news.rb

_Please provide the URL for the JIRA ticket._
Add  news filtration via category, add search via news, add pagination.
Created partials which provide required functions.

Lvruby 14 2 Added filtering, pagination and search functionality to news.

---

app/views/news/index.html.haml

Displayed News images in index page
Changes in news/index.html.haml

FiX in news index page

---

config/routes.rb
db/schema.rb

_Please provide the URL for the JIRA ticket._
_Please list your code reviewers here._
_Please provide the details of the issue._
_Please provide a summary of your change here._

Deleted changes from schema.rb

---

config/initializers/will_paginate.rb

https://github.com/mislav/will_paginate/issues/174#issuecomment-2380779

Fix error in rails_admin with will_paginate gem

---

app/controllers/news_controller.rb
app/models/news.rb
app/views/news/_news.html.haml
app/views/news/index.html.haml
app/views/news/index.js.haml
config/locales/en.yml
config/locales/uk.yml

http://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=979&view=planning&selectedIssue=LVRUBY-100
Added ability to see the most popular news
Added AJAX requests to news.js file
Created index.js.haml for rendering news partial with AJAX

LVRUBY-100: Sorting news by views

---

app/mailers/messages_mailer.rb

_Please provide the URL for the JIRA ticket._
_Please list your code reviewers here._
_Please provide the details of the issue._
_Please provide a summary of your change here._

FIX: Mailer for comments

---

app/assets/stylesheets/pages/users.scss
app/controllers/users_controller.rb
app/models/user.rb
app/views/shared/_header.html.haml
app/views/users/_role.html.haml
app/views/users/_search.html.haml
app/views/users/_search_form.html.haml
app/views/users/_user.html.haml
app/views/users/index.html.haml
app/views/users/index.js.haml
config/locales/en.yml
config/locales/uk.yml
spec/controllers/users_controller_spec.rb
spec/models/user_spec.rb

http://ssu-jira.softserveinc.com/secure/RapidBoard.jspa?rapidView=979&view=planning&selectedIssue=LVRUBY-118
Search by users
Added AJAX requests to users.js file
Created index.js.haml for rendering users partial with AJAX

Add searches by users

---

app/controllers/email_change_requests_controller.rb
app/controllers/events_controller.rb
app/controllers/news_controller.rb
app/views/email_change_requests/_form.html.haml
app/views/email_change_requests/new.html.haml
app/views/events/_event.html.haml
app/views/events/index.html.haml
app/views/events/user_events.html.haml
app/views/news/_news.html.haml
app/views/news/_selector.html.haml
app/views/news/index.html.haml
app/views/news/user_news.html.haml
app/views/users/_description.html.haml
app/views/users/_form.html.haml
app/views/users/_menu.html.haml
app/views/users/_password.html.haml
app/views/users/_role.html.haml
app/views/users/_search.html.haml
app/views/users/_search_form.html.haml
app/views/users/edit.html.haml
app/views/users/edit_email.html.haml
app/views/users/edit_password.html.haml
app/views/users/show.html.haml
config/locales/en.yml
config/locales/uk.yml
config/routes.rb
db/schema.rb

_Please provide the URL for the JIRA ticket._
_Please list your code reviewers here._
Show news, events in user profile
Add news and events in user profile.
Change view in search users, news.

Add show news, events to profile

---

app/controllers/messages_controller.rb
app/views/messages_mailer/contact_us_email.html.haml
spec/controllers/messages_controller_spec.rb
spec/mailers/messages_mailer_spec.rb

Changed deliver now to deliver later
Changes in messages_contoller.rb
Changes in tests

Fix message mailer

---

app/controllers/events_controller.rb
app/models/event.rb
app/models/user.rb
app/views/events/show.html.haml
config/locales/en.yml
config/locales/uk.yml
config/routes.rb
db/migrate/20190517050904_create_users_events.rb
db/schema.rb
spec/controllers/events_controller_spec.rb
spec/models/event_spec.rb

[LVRUBY-108](https://ssu-jira.softserveinc.com/browse/LVRUBY-108)
Add event subscription
Add users the ability to subscribe to events

LVRUBY-108: Add event subscription
